#!/bin/bash

# A simple shell script to run the ImageTerrier Basic Searcher tool
#
# @author Jonathon Hare

bin=`dirname "$0"`

java -Dimageterrier.log.level=info -Xmx8G -cp "`ls $bin/target/ImageTerrierTools-3.6-SNAPSHOT-jar-with-dependencies.jar`" org.imageterrier.basictools.BasicSearcher ${1+"$@"}
